# Generated by Django 5.1.7 on 2025-08-28 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0002_alter_orderdetailmodel_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering_app.basketordermodel'),
        ),
    ]
