# Generated by Django 5.1.7 on 2025-03-26 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('slug', models.SlugField(verbose_name='عنوان در مرورگر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='authors/', verbose_name='تصویر')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('birth', models.DateField(verbose_name='تریخ تولد ')),
                ('language', models.CharField(max_length=50, verbose_name='زبان')),
                ('number_books', models.IntegerField(verbose_name='تعداد کتاب های نویسنده')),
                ('number_awards', models.IntegerField(verbose_name='تعداد جوایز نویسنده')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(verbose_name='عنوان در مرورگر')),
                ('category', models.ManyToManyField(to='product_app.categorymodel', verbose_name='ژانر کتاب های  نویسنده')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('publication_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('publisher', models.CharField(max_length=50, verbose_name='ناشر')),
                ('length', models.IntegerField(verbose_name='طول کتاب')),
                ('version', models.IntegerField(verbose_name='نسخه')),
                ('ISBN', models.IntegerField(verbose_name='شابک')),
                ('language', models.CharField(max_length=50, verbose_name='زبان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('seller', models.CharField(max_length=50, verbose_name='فروشنده')),
                ('is_off', models.IntegerField(verbose_name='تخفیف(بصورت درصد)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('slug', models.SlugField(verbose_name='عنوان در مرورگر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.authormodel', verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.categorymodel', verbose_name='دسته بندی کتاب')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
