# Generated by Django 5.1.7 on 2025-03-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='birth',
            field=models.IntegerField(verbose_name='تاریخ تولد(سال) '),
        ),
    ]
