# Generated by Django 5.1.7 on 2025-03-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_authormodel_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='is_off',
            field=models.IntegerField(blank=True, verbose_name='تخفیف(بصورت درصد)'),
        ),
    ]
