# Generated by Django 5.1.7 on 2025-04-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_productmodel_is_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='product_app.categorymodel', verbose_name='ژانر کتاب های  نویسنده'),
        ),
    ]
