# Generated by Django 5.1.7 on 2025-04-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_productmodel_is_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authormodel',
            name='language',
        ),
    ]
