# Generated by Django 5.1.7 on 2025-04-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_remove_authormodel_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='language',
            field=models.CharField(max_length=50, null=True, verbose_name='زبان'),
        ),
    ]
