# Generated by Django 5.1.7 on 2025-04-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_authormodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='category',
            field=models.ManyToManyField(to='product_app.categorymodel', verbose_name='ژانر کتاب های  نویسنده'),
        ),
    ]
