# Generated by Django 5.1.7 on 2025-07-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_authormodel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, verbose_name='عنوان در مرورگر'),
        ),
    ]
