# Generated by Django 5.1.7 on 2025-07-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_productmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='count',
            field=models.PositiveIntegerField(null=True, verbose_name='تعداد'),
        ),
    ]
