# Generated by Django 5.1.7 on 2025-09-09 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_productmodel_is_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='is_off',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف(بصورت درصد)'),
        ),
    ]
