# Generated by Django 5.1.7 on 2025-04-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_alter_contactmodel_email_alter_contactmodel_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
