# Generated by Django 5.1.7 on 2025-04-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(blank=True, verbose_name='پیام'),
        ),
    ]
