# Generated by Django 5.1.7 on 2025-08-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_usermodel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='پروفایل'),
        ),
    ]
