# Generated by Django 5.1.7 on 2025-09-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_usermodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/User Profile Icon.png', null=True, upload_to='avatars/', verbose_name='پروفایل'),
        ),
    ]
