# Generated by Django 5.1.7 on 2025-04-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('craete_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='articles/%Y')),
                ('img2', models.ImageField(upload_to='articles/%Y')),
                ('para1', models.TextField(blank=True, null=True)),
                ('para2', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'مقاله ',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
