# Generated by Django 5.1.7 on 2025-04-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='slug',
            field=models.SlugField(null=True, verbose_name='عنوان در مرورگر'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='author',
            field=models.CharField(max_length=50, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='craete_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ '),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='img1',
            field=models.ImageField(upload_to='articles/%Y', verbose_name='اصویر اول'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='img2',
            field=models.ImageField(upload_to='articles/%Y', verbose_name='تصویر دوم'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='para1',
            field=models.TextField(blank=True, null=True, verbose_name='پاراگراف دوم'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='para2',
            field=models.TextField(blank=True, null=True, verbose_name='پاراگراف دوم'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
    ]
