# Generated by Django 5.1.7 on 2025-05-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_articlemodel_slug_alter_articlemodel_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='author',
        ),
    ]
