# Generated by Django 5.1.7 on 2025-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0005_alter_articlemodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, verbose_name='عنوان در مرورگر'),
        ),
    ]
