# Generated by Django 5.1.7 on 2025-06-11 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('img1', models.ImageField(upload_to='articles/%Y', verbose_name='تصویر اول')),
                ('img2', models.ImageField(upload_to='articles/%Y', verbose_name='تصویر دوم ')),
                ('para1', models.TextField(verbose_name='پاراگراف اول')),
                ('para2', models.TextField(verbose_name='پاراگراف دوم')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('slug', models.SlugField(verbose_name='عنوان در مرورگر')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
