# Generated by Django 5.1.7 on 2025-06-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articels_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
    ]
