# Generated by Django 5.1.7 on 2025-06-16 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articels_app', '0005_alter_articlemodel_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('is_publish', models.BooleanField(default=False, verbose_name='انتشار')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articels_app.articlemodel', verbose_name='مقاله')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها ',
            },
        ),
    ]
