# Generated by Django 5.1.7 on 2025-06-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articels_app', '0007_alter_articlemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ['id'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
