# Generated by Django 5.1.7 on 2025-06-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articels_app', '0008_alter_articlemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecommentmodel',
            options={'ordering': ['id'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها '},
        ),
    ]
